# Colino Configuration
# Copy this to ~/.config/colino/config.yaml or keep in project root

# RSS Feed Sources
rss:
  feeds:
    - https://hnrss.org/frontpage

youtube:
  # Rotating proxy configuration for transcript fetching (optional)
  # Helps avoid rate limiting when fetching many transcripts
  proxy:
    enabled: false
    # Webshare.io rotating proxy configuration
    # webshare:
    #   username: "your_username"
    #   password: "your_password"

# AI/LLM Configuration
ai:
  stream: false

  # Model settings
  model: "gpt-5-mini"

  article_prompt: |
    You are an expert news curator and summarizer.
    Create an insightful summary of the article content below.
    The content can come from news articles, youtube videos transcripts or blog posts.
    Format your response in clean markdown with headers and bullet points if required.

    ## Article {{ article.title }}
    **Source:** {{ article.source }} | **Published:** {{ article.published }}
    **URL:** {{ article.url }}

    **Content:**
    {{ article.content }}

# Database
database:
  path: "colino.db"
