# Colino Configuration
# Copy this to ~/.config/colino/config.yaml or keep in project root

# RSS Feed Sources
rss:
  feeds:
    - https://hnrss.org/frontpage

youtube:
  # Rotating proxy configuration for transcript fetching (optional)
  # Helps avoid rate limiting when fetching many transcripts
  proxy:
    enabled: false
    # Webshare.io rotating proxy configuration
    # webshare:
    #   username: "your_username"
    #   password: "your_password"

# AI/LLM Configuration
ai:
  stream: false
  # OpenAI API key - set OPENAI_API_KEY environment variable (recommended)
  # or uncomment and set here (not recommended for production)
  # openai_api_key: "your_key_here"

  # Model settings
  model: "gpt-5-mini"
  extract_web_content: true

  # Digest auto-save
  auto_save: true
  save_directory: "digests"

  article_prompt: |
    You are an expert news curator and summarizer.
    Create an insightful summary of the article content below.
    The content can come from news articles, youtube videos transcripts or blog posts.
    Format your response in clean markdown with headers and bullet points if required.

    ## Article {{ article.title }}
    **Source:** {{ article.source }} | **Published:** {{ article.published }}
    **URL:** {{ article.url }}

    **Content:**
    {{ article.content }}

  youtube_prompt: |
    You are an expert video summarizer.
    I'm going to send you the transcript of a video and you'll summarize it for me.
    Format your response in clean markdown with headers and bullet points if required.

    Video transcript: {{ transcript }}

    If possible, find links to existing theories, philosophic positions, trends and suggest possible follow ups. If not, don't mention any of that.
    Do not offer any follow up help.

# Database
database:
  path: "colino.db"
