name: Go CI

on:
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'
      - name: Build
        run: go build ./...
      - name: Vet
        run: go vet ./...
      - name: Format check
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            echo "Go files not formatted:" && gofmt -l . && exit 1; fi
      - name: Test
        run: go test ./...

