name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'
          cache: true
      - name: Cache Go modules
        id: cache-go
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

    - name: Check cache hit
        run: |
          if [ "${{ steps.cache-go.outputs.cache-hit }}" == "true" ]; then
            echo "✅ Go cache hit! Dependencies restored from cache."
          else
            echo "❌ Go cache miss. Dependencies will be downloaded."
          fi
      - name: Build
        run: go build ./...
      - name: Vet
        run: go vet ./...
      - name: Format check
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            echo "Go files not formatted:" && gofmt -l . && exit 1; fi
      - name: Test
        run: go test ./...

